stages:
  - test

variables:
  PYTHON_VERSION: "3.9"

before_script:
  - apt-get update -y
  - apt-get install -y python3 python3-pip python3-venv
  - python3 -m venv venv
  - source venv/bin/activate
  - pip install requests

test:
  stage: test
  script:
    - echo "Running the API test script..."
    - python3 "./API Request/API Request/API_AUTOMATION_REQRES/api_automation.py"

  artifacts:
    paths:
      - result.log  # Optional: Specify any files you want to keep as artifacts
    expire_in: 1 week

  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "master"'  # Trigger on both main and master branches
