name: API Test

on:
  push:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install requests

      - name: Run API Test
        run: |
          echo "Running the API test script..."
          python3 "./API Request/API Request/API_AUTOMATION_REQRES/api_automation.py"
